name: "WebApp"
mode: "dev"
port: 8081
version: "v1.0.0.8"

log:
  level: "debug"
  filename: "WebApp_log"
  max_size: 200
  max_age: 50
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "mch123"
  dbname: "sql_demo"
  max_open_conns: 10
  max_idle_conns: 10
redis:
  host: "127.0.0.1"
  port: 16379
  password: "mch123"
  pool_size: 110
  db: 0